# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('totalspent', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('itemno', models.IntegerField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=100)),
                ('itemdescription', models.TextField()),
                ('itemimage', models.URLField()),
                ('itemprice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderdetailsno', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50)),
                ('itemno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatapp.Menus')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderno', models.IntegerField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('orderamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customerno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('resno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('resdescription', models.TextField()),
                ('last_modified_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='orderno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatapp.Orders'),
        ),
        migrations.AddField(
            model_name='menus',
            name='resno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatapp.Restaurants'),
        ),
    ]
