# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='itemdescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='itemimage',
            field=models.URLField(blank=True),
        ),
    ]
