# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import eatapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0005_orders_orderend'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='rescode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='respassword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menus',
            name='itemimage',
            field=models.ImageField(blank=True, null=True, upload_to=eatapp.models.upload_location),
        ),
    ]
