# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0006_auto_20161005_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='resno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eatapp.Restaurants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='resno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eatapp.Restaurants'),
            preserve_default=False,
        ),
    ]
